################################################################################
# 02_create_serology_phenotypes.R
################################################################################
#  Purpose:
#    • Read posterior seropositivity probabilities generated by
#      01_serology_power_analysis.R (to be saved as CSV/RDS).
#    • Select a manual set of antigens to include in the GWAS.
#    • Produce:
#        1. phenotypes_for_gwas.tsv  (FID IID + one column per antigen)
#        2. weights_<antigen>.txt    (IID weight)  — one file per antigen
#    • All file names/paths can be changed in the "CONFIGURATION" block below.
#
#  Quick usage:
#    Rscript 02_create_serology_phenotypes.R
################################################################################

## ---- packages --------------------------------------------------------------
if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
pacman::p_load(dplyr, tidyr, readr, tibble, stringr, purrr)

## ---- CONFIGURATION ---------------------------------------------------------
# Path to the long-format posterior probability file produced by script 01.
# Expected columns: eid, Antibody, PosteriorProb
posterior_file <- "antibody_posteriors_long.csv"   # change if necessary

# Output directory for weight files
weights_dir <- "weights_files"
if (!dir.exists(weights_dir)) dir.create(weights_dir)

# Manual inclusion list -------------------------------------------------------
#  EDIT THIS VECTOR after reviewing the diagnostic plots.
#  Only antigens listed here will be emitted.
#  Example: included_antigens <- c("cmv_pp150", "ebv_vca", "hp_omp")

included_antigens <- c(  # <<<<<<  PLACEHOLDER — fill in manually  >>>>>>
)

if (length(included_antigens) == 0) {
  stop("\n[ABORT]  'included_antigens' vector is empty.  Please edit the script \
       after deciding which antigens to keep.")
}

## ---- load posterior probabilities -----------------------------------------
cat("Reading posterior probabilities from:", posterior_file, "\n")
post_long <- read_csv(posterior_file, show_col_types = FALSE)

required_cols <- c("eid", "Antibody", "PosteriorProb")
if (!all(required_cols %in% names(post_long))) {
  stop("Input file missing required columns: ", paste(setdiff(required_cols, names(post_long)), collapse=","))
}

## ---- filter to included antigens ------------------------------------------
post_long <- post_long %>% filter(Antibody %in% included_antigens)
if (nrow(post_long) == 0) stop("No rows left after filtering — check antigen names.")

## ---- wide phenotype table --------------------------------------------------
phenotype_wide <- post_long %>%
  mutate(FID = eid, IID = eid) %>%
  select(FID, IID, Antibody, PosteriorProb) %>%
  pivot_wider(names_from = Antibody, values_from = PosteriorProb)

# Save phenotype file
pheno_out <- "phenotypes_for_gwas.tsv"
write_tsv(phenotype_wide, pheno_out, na = "NA")
cat("Phenotype file written to", pheno_out, "(", nrow(phenotype_wide), "samples )\n")

## ---- weight files (one per antigen) ---------------------------------------
post_long %>%
  mutate(IID = eid) %>%
  group_by(Antibody) %>%
  group_walk(~{
    out_path <- file.path(weights_dir, paste0("weights_", .y$Antibody, ".txt"))
    write_tsv(.x %>% select(IID, weight = PosteriorProb), out_path, col_names = FALSE)
    cat("  •", out_path, "\n")
  })
cat("Weight files written to", weights_dir, "\n")

cat("\n[Done] You can now feed 'phenotypes_for_gwas.tsv' and the weight files to quickdraws/PLINK.\n") 